filme/urls.py
from django.urls import include, path, reverse_lazy

from .views import Detalhesfilme, Homefilmes, Homepage, Pesquisafilme, Paginaperfil, Criarconta, Videofilme
from django.contrib.auth import views as auth_view


app_name = "filme"


urlpatterns = [
    path('', Homepage.as_view(), name="home"),
    path('filmes/', Homefilmes.as_view(), name="homefilmes"),
    path('filmes/<int:pk>', Detalhesfilme.as_view(), name="detalhesfilme"),
    path('pesquisa/', Pesquisafilme.as_view(), name="pesquisafilme"),
    path('login/', auth_view.LoginView.as_view(template_name="login.html"), name="login"),
    path('logout/', auth_view.LogoutView.as_view(template_name="logout.html"), name="logout"),
    path('editarperfil/<int:pk>', Paginaperfil.as_view(), name="editarperfil"),
    path('criarconta/', Criarconta.as_view(), name="criarconta"),
    path('mudarsenha/<int:pk>', auth_view.PasswordChangeView.as_view(template_name='editarperfil.html',
                                                             success_url=reverse_lazy('filme:homefilme')), name="mudarsenha"),
    path('video/<int:pk>', Videofilme.as_view(), name="video")
] 

pobrix/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('filme.urls', namespace='filme')),
] 

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

filme/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import AbstractUser
# Create your models here.



# lista de categorias 
LISTA_CATEGORIAS = (
    ("Acao", "Ação"),
    ("Anime", "Anime"),
    ("Aventura", "Aventura"),
    ("Comedia", "Comédia"),
    ("Documentario", "Documentário"),
    ("Infantil", "Infantil"),
    ("Romance", "Romance"),
    ("Terror", "Terror"),
    ("Drama","Drama"),
    )
# modelo de filme
class Filme(models.Model):
    titulo = models.CharField(max_length=100)
    thumb = models.ImageField(upload_to='thumbs-filmes')
    descricao = models.TextField(max_length=1000)
    categoria = models.CharField(max_length=16, choices=LISTA_CATEGORIAS)
    visualizacoes = models.IntegerField(default=0)
    data_criacao = models.DateTimeField(default=timezone.now)

# funcao de mostra o nome do filme 
    def __str__(self):
        return self.titulo






#Criar episódio

class Episodio(models.Model):
    filme = models.ForeignKey("Filme", related_name="episodios", on_delete=models.CASCADE)
    titulo = models.CharField(max_length=100)
    video = models.URLField()
    
    # funcao de mostra o nome do episodio
    def __str__(self):
        return self.filme.titulo + " - " + self.titulo
    


#Criar usuário 


class Usuario(AbstractUser):
    filmes_vistos = models.ManyToManyField("Filme")
    
    

filme/forms.py
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario
from django import forms


class FormHome(forms.Form):
    email = forms.EmailField(label=False)


#criando formulario de criação de usuário padrão
class CriarContaForm(UserCreationForm):
    email = forms.EmailField()

    


    class Meta:
        model = Usuario
        fields = ('username', 'email', 'password1', 'password2')#criando personalizado requisitando email

filme/views.py
from django.shortcuts import render, redirect, reverse
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Filme, Usuario
from .forms import CriarContaForm, FormHome


# Create your views here.
#função que faz a requisição e retorna home.html FBV
#def homepage(request):
#   return render(request, "home.html" )

# metodo de classe irá usa um views pre feita do generic e quando é usado TemplateView é só para mostra um template listview irá mostra uma lista do model.
class Homepage(FormView): 
    template_name = "home.html"
    form_class = FormHome

    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('filme:homefilmes')

        else:

            return super().get(request, *args, **kwargs)
    #função de acordo com email que usuário coloca no imput da homepage ele redireciona o url .
    def get_success_url(self):
        email = self.request.POST.get("email")
        usuarios = Usuario.objects.filter(email=email)
        if usuarios:
            return reverse('filme:login')
        else:
            return reverse('filme:criarconta')    


class Homefilmes(LoginRequiredMixin, ListView):
    template_name = "homefilmes.html"
    model = Filme
    #object_list vez de retorna list_filmes

class Detalhesfilme(LoginRequiredMixin, DetailView):
    template_name = "detalhesfilme.html"
    model = Filme
    
    #função para contabilizar uma visualização.
    def get(self, request, *args, **kwargs):
        filme = self.get_object()
        filme.visualizacoes += 1 # somo a visualizacao.
        filme.save() # salvar a mudança no banco de dados.
        usuario = request.user
        usuario.filmes_vistos.add(filme) # irá adicionar os filmes visto pelo usuario e irá contalibizar no bd.


        return super().get(request, *args, **kwargs) #redireciona o usuario para url final. 

    
    # DetailsView irá criar 1 item para cada modelo
    def get_context_data(self, **kwargs):
        context = super(Detalhesfilme, self).get_context_data(**kwargs)
        #filtrar a minha tabela de filmes pegando a categoria dos filmes para virar um filme relacionados .
        
        filmes_relacionados = Filme.objects.filter(categoria=self.get_object().categoria)[0:5]
        context['filmes_relacionados'] = filmes_relacionados
        return context


class Pesquisafilme(LoginRequiredMixin, ListView):
    template_name = "pesquisa.html"
    model = Filme
    #editando object_list
    def get_queryset(self):
        pesquisa = self.request.GET.get('query')
        if pesquisa:
            object_list = self.model.objects.filter(titulo__icontains=pesquisa)
            return object_list
        else:
            
            return None


class Paginaperfil(LoginRequiredMixin, UpdateView):
    template_name = "editarperfil.html"
    model = Usuario
    fields = ['first_name', 'last_name', 'email']
    
    def get_success_url(self):
        
        return reverse('filme:homefilmes')

class Criarconta(FormView):
    template_name = "criarconta.html"
    form_class = CriarContaForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)

    #se a requisição for um sucesso ele retornara o link do filme:login
    def get_success_url(self):
        return reverse('filme:login')


class Videofilme(LoginRequiredMixin, DetailView):
    template_name = "video.html"
    model = Filme

    def get_success_url(self):
        return redirect('filme:video')

    

filme/templates/criarconta.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}

Criar Conta PobriX

{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
            <legend class="border-bottom mb-4">Crie uma conta para continuar</legend>
                {{ form|crispy }}
                
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white w-full md:text-lg rounded-md" type="submit">Criar Conta</button>
        </form>

    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center"></ul>
    <li>&copy; 2022</li>
        <li> Feito com Python (Django)</li>
        <li>Equipe Ulysses,Raphael Trilha Web Django.</li>
    </ul>
</footer>



{% endblock %}

filme/templates/detalhesfilme.html
{% extends 'base.html' %}

{% block titulo %}

{{ object.titulo }} - PobriX

{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <section class="h-screen relative bg-no-repeat pb-8 pl-6 flex  items-end bg-cover" style="background-image: url('{{ object.thumb.url }}');">
        <div>
            <h2 class="text-6xl font-semibold text-white my-4">
                {{ object.titulo }} 
            </h2>
            <p class=" w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ object.descricao|slice:":100" }}...
            </p>
            <div class="flex my-4">
                <a href="{% url 'filme:video' filme.id %}">
                    <button class="flex items-center bg-zinc-50 hover:bg-red-500 py-2 px-5 rounded-md" style="color:black;">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 
    <section class="bg-primary_black flex justify-center py-10">
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-3xl font-medium">
                Descrição
            </h2>
            <div class="flex justify-left items-center min-w-full">
                <p class="text-gray-100 text-lg">
                    {{ object.descricao }}
                    <br>
                    Visualizações: {{ object.visualizacoes }}
                </p>
            </div>
            <div style='margin-top:2rem;margin-bottom:2rem;'>
                <h2 class="text-gray-200 text-3xl font-medium">
                    Episódios
                </h2>
                {% if not object.episodios.all %}
                <h3 class="text-lg">
                    Em breve
                </h3>
                {% else %}
                {% for episodio in object.episodios.all %}
                <h3 class="text-lg">
                    <a href="{% url 'filme:video' filme.id  %}">
                        <p>{{ forloop.counter }} - {{ episodio.titulo }}</p>
                    </a>
                </h3>
                {% endfor %}
                {% endif %}
            </div>
        </div>
    </section>
    {% if filmes_relacionados %}
    <section class="flex justify-center py-10">
        <div class="p-8 w-10/12 relative">
            <h2 class="text-gray-200 text-2xl font-medium">
                Relacionados
            </h2>
            <div class="flex flex-wrap items-center justify-center min-w-full">
                {% for filme in filmes_relacionados %}
                <div class="filme m-4 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.pk %}">
                        <img src="{{ filme.thumb.url }}" class="hover:scale-110 transition ease-in-out object-cover w-full h-full" alt="">
                    </a>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
    {% endif %}
    
{% endblock %}

filme/templates/editarperfil.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}
Editar Perfil 
{% endblock %}

{% block head %}

{% endblock %}

{% block content %}
<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-center bg-cover bg-fixed"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <h2 class="text-2xl text-red-500">{{ user.username }}</h2>
        <form method="post" class="conta">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Edite os campos abaixo para editar seu perfil</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-red-600 py-1 px-3 text-white md:text-lg rounded-md" type="submit">Editar Perfil</button>
        </form>
        <small class="py-3 text-yellow-300"><a href="{% url 'filme:mudarsenha' user.pk %}">Quer mudar sua senha? Clique aqui.</a></small>
    </div>
</header>

<footer class="px-5 py-10">
    <ul class="flex justify-between items-center text-xs sm:text-sm">
        <li>&copy; 2022</li>
        <li> Feito com Python (Django)</li>
        <li>
            
        </li>
    </ul>
</footer>

{% endblock %}

filme/templates/home.html
{% extends 'base.html' %}
{% load static %}


{% block titulo %}

Inicio - PobriX

{% endblock %}

{% block head %}
    <style>

    #id_email{
        width: 100%;
        color: black;
        border-radius: 2px;
        padding: 5px ;
    }

    </style>
    
{% endblock %}

{% block content %}

<header class="min-h-screen bg-black bg-opacity-50 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">

        <h1 class="font-semibold text-4xl md:text-5xl w-10/12 md:w-3/4 text-center">
            Filmes e séries da Pobrix, tudo em um só lugar.
        </h1>
        <h3 class="text-xl md:text-xl py-5">
            Assista onde quiser. Cancele quando quiser.
        </h3>
        <h4 class="text-sm md:text-lg pb-3">
            Quer começar? Coloque seu e-mail abaixo para acessar.
        </h4>

        <div class="w-full flex justify-center">
            <div class="flex justify-center items-center w-11/12 md:w-10/12">
                <form method="post" class="w-6/12 justify-center">
                    {% csrf_token %}
                    <div class="flex flex-grow items-stretch">
                        {{ form }}
                    <button class="bg-red-600 font-medium md:font-normal flex justify-center items-center py-2 px-3 md:px-0 rounded-br-sm rounded-tr-sm md:text-2xl" type="submit">
                        <span>
                            Acessar
                        </span>
                        <ion-icon name="chevron-forward-outline" class="text-2xl"></ion-icon>
                    </button>
                    </div>
                </form>
                </a>
            </div>
        </div>

    </div>
</header>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10 ">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Divirta-se na sua TV.
        </h2>
        <h5 class="md:text-xl text-lg">
            Assista em Smart TVs, Playstation, Xbox, Chromecast, Apple TV, Blu-ray players e muito mais.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/tv.png' %}" class="w-8/12" alt="tv">
    </div>
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class='md:w-1/2 flex justify-center items-center '>
        <img src="{% static 'images/mobile.jpg' %}" class="w-8/12" alt="mobile">
    </div>

    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Baixe seus programas para assistir offline. 
        </h2>
        <h5 class="md:text-xl text-lg">
            Salve seus favoritos facilmente e sempre tenha algo para assistir.
        </h5>
    </div>
    
</section>

<section class='flex flex-col md:flex-row items-center border-gray-900 border-b-8' style="min-height: 70vh;">
    <div class="md:w-1/2 flex flex-col justify-center text-center md:text-left p-5 md:p-10">
        <h2 class="md:text-5xl text-4xl font-semibold mb-4">
            Crie perfis para crianças.
        </h2>
        <h5 class="md:text-xl text-lg">
            Envie as crianças em aventuras com seus personagens favoritos em um espaço feito apenas para elas - grátis com sua assinatura.
        </h5>
    </div>
    <div class='md:w-1/2 flex justify-center items-center'>
        <img src="{% static 'images/netflix-kids.png' %}" class="w-8/12" alt="kids">
    </div>
</section>
<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2022</li>
        <li> Feito com Python (Django)</li>
        <li>Equipe Ulysses,Raphael Trilha Web Django.</li>
    </ul>
</footer>


{% endblock %}

filme/templates/homefilmes.html
{% extends 'base.html' %}

{% block titulo %}

Filmes - PobriX

{% endblock %}

{% block head %}
    <style>
@import url('https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700;900&display=swap');

html {
  scroll-behavior: smooth;
}

body {
  margin: 0;
  background-color: rgb(49, 49, 49);
  font-family: 'Roboto', sans-serif;
}

h1 {
  
  color: red;
  text-align: center;
}

.wrapper {
  display: grid;
  grid-template-columns: repeat(3,100%);
  overflow:hidden;
  scroll-behavior: smooth;

}
    
    
    
    
      
    



    </style>

{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <section 
    class="h-screen pb-8 pl-6 flex items-end bg-fixed bg-center bg-cover bg-black bg-opacity-50 bg-blend-overlay"
        style="background-image: url('{{ filme_destaque.thumb.url }}');">
        <div>
            <h2 class="text-4xl sm:text-6xl font-semibold text-white my-4">
                {{ filme_destaque.titulo }}
            </h2>
            <p class="w-11/12 md:w-5/12 font-medium text-white my-4">
                {{ filme_destaque.descricao|slice:":50" }}...
            </p>
            <div class="flex my-4">
                <a href="{% url 'filme:video' filme_destaque.pk %}">
                    <button class="flex items-center bg-zinc-50 hover:bg-red-500 py-2 px-5 rounded-md" style="color:black;">
                        <ion-icon name="play" class="text-2xl"></ion-icon>
                        <span class="ml-3 font-medium ">
                            Play
                        </span>
                    </button>
                </a>
            </div>
        </div>
    </section> 

    <!-- Novos filmes-->
    <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Novo
            </h2>
            <div class="wrapper">
              <section id="section1" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2" class="arrow__btn text-6xl page">‹</a>
                {% for filme in lista_filmes_recentes %}
                {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                {% endif %}
                {% endfor %}
                    <a href="#section2" class="arrow__btn text-6xl">›</a>
              </section>
                {% if lista_filmes_recentes|length > 4  %}
                  <section id="section2" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1" class="arrow__btn text-6xl">‹</a>
                      {% for filme in lista_filmes_recentes %}
                      {% if forloop.counter > 4 %}
                        <div class="item h-64 w-1/4 m-4">
                            <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                              <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                            </a>
                        </div>
                      {% endif %}
                      {% endfor %}
                    <a href="#section1" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>


        </div>
    </section>
    <!-- filme em alta-->
    <section class='bg-primary_black flex justify-center py-10'>
      <div class="p-8 w-10/12 relative" >
          <h2 class="text-gray-200 text-2xl font-medium">
              Em Alta
          </h2>
          <div class="wrapper">
            <section id="section1emalta" class="flex flex-nowrap items-center justify-center space-x-8">
              <a href="#section2emalta" class="arrow__btn text-6xl page">‹</a>
              {% for filme in lista_filmes_emalta %}
              {% if forloop.counter < 5 %}
                <div class="item h-64 w-1/4 m-4">
                    <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                      <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                    </a>
                </div>
              {% endif %}
              {% endfor %}
                  <a href="#section2emalta" class="arrow__btn text-6xl">›</a>
            </section>
              {% if lista_filmes_emalta|length > 4  %}
                <section id="section2emalta" class="flex flex-nowrap items-center justify-center">
                  <a href="#section1emalta" class="arrow__btn text-6xl">‹</a>
                    {% for filme in lista_filmes_emalta %}
                    {% if forloop.counter > 4 %}
                      <div class="item h-64 w-1/4 m-4">
                          <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                            <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                          </a>
                      </div>
                    {% endif %}
                    {% endfor %}
                  <a href="#section1emalta" class="arrow__btn text-6xl">›</a>
                </section>
              {% endif %}
          </div>
        </div>
      </section>
      
      <!--filmes visto pelo usuário-->
      <section class='bg-primary_black flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Continuar Assistindo
            </h2>
            <div class="wrapper">
              <section id="section1vistos" class="flex flex-nowrap items-center justify-center space-x-8">
                <a href="#section2vistos" class="arrow__btn text-6xl page">‹</a>
                {% for filme in request.user.filmes_vistos.all %}
                {% if forloop.counter < 5 %}
                  <div class="item h-64 w-1/4 m-4">
                      <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                        <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                      </a>
                  </div>
                {% endif %}
                {% endfor %}
                    <a href="#section2vistos" class="arrow__btn text-6xl">›</a>
              </section>
                {% if request.user.filmes_vistos.all|length > 4  %}
                  <section id="section2vistos" class="flex flex-nowrap items-center justify-center">
                    <a href="#section1vistos" class="arrow__btn text-6xl">‹</a>
                      {% for filme in request.user.filmes_vistos.all %}
                      {% if forloop.counter > 4 %}
                        <div class="item h-64 w-1/4 m-4">
                            <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                              <img src="{{ filme.thumb.url }}" class="rounded-md w-full h-full object-cover">
                            </a>
                        </div>
                      {% endif %}
                      {% endfor %}
                    <a href="#section1vistos" class="arrow__btn text-6xl">›</a>
                  </section>
                {% endif %}
            </div>
          </div>
        </section>

</main>




{% endblock %}

filme/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block titulo %}

Login Pobrix

{% endblock %}

{% block content %}

<header class="min-h-screen bg-black bg-opacity-75 bg-blend-overlay showcase border-gray-600 border-b-8 flex justify-center items-center bg-no-repeat"  style="background-image: url('{% static 'images/background_netflix.jpg' %}');">
    <div class="z-10 h-full py-32 md:py-0 text-gray-100 text-center flex items-center flex-col">
        <form method="post">
           {% csrf_token %}
           
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Faça Login para continuar</legend>
                {{ form|crispy }}
            </fieldset>
            <button class="bg-red-600 py-1 my-2 px-3 w-full text-white md:text-lg rounded-md" type="submit">Fazer Login</button>
        </form>
        <small>
            Não tem uma conta ainda? <p><a href="{% url 'filme:criarconta' %}">Clique aqui para criar uma conta</a></p>
        </small>
    </div>
</header>

<footer class=" px-5 py-10 ">
    <ul class="flex justify-between items-center">
        
        <li>&copy; 2022</li>
        <li> Feito com Python (Django)</li>
        <li>Equipe Ulysses,Raphael Trilha Web Django.</li>
    </ul>
</footer>



{% endblock %}

filme/templates/pesquisa.html
{% extends 'base.html' %}

{% block titulo %}

Pesquisa de Filmes

{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <section class='bg-primary_black  min-h-screen flex justify-center py-10'>
        <div class="p-8 w-10/12 relative" >
            <h2 class="text-gray-200 text-2xl font-medium">
                Resultados da Busca
            </h2>
            {% for filme in object_list %}
            <div class="flex flex-wrap items-center min-w-full movie_lis">
                <div class="m-4 bg-blue-500 overflow-hidden flex-shrink-0 rounded-md cursor-pointer h-64 w-96">
                    <a href="{% url 'filme:detalhesfilme' filme.id  %}">
                            <img src="{{ filme.thumb.url }}" class="object-cover w-full h-full " alt="">
                    </a>
                    </div>
            {% endfor %}
            </div>


        </div>
    </section>
</main>

{% endblock %}

filme/templates/video.html
{% extends 'base.html' %}

{% block titulo %}

Play - PobriX

{% endblock %}

{% block head %}

{% endblock %}

{% block content %}

<main class='bg-primary_black min-h-screen w-full'>
    <div class="flex py-12 justify-center">
     <iframe width="100%" height="575px" src="{{object.episodios.first.video}}" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
        
    </div>
</main>



{% endblock %}

templates/navbar.html
<!--NAVBAR -->
{% load static %}

<nav class="w-full flex justify-between items-center py-1 px-4 fixed z-50">
  <div class="w-6/12">
    <a href="/" class="flex py-1 items-center">
      <img
        class="w-3/12"
        src="{% static 'images/logo.png' %}"
        alt="logo"
      />
    </a>
  </div>
  {% if user.is_authenticated %}
  <div class="w-6/12 flex flex-nowrap justify-end">
    <div class="mr-2">
      <form method="get" action="{% url 'filme:pesquisafilme' %}">
        <input
          type="text"
          class="py-1 px-2 rounded-md text-black"
          name="query"
          value="{{ request.Get.query }}"
          placeholder="Pesquisar..."
        />
        <input type="submit" value="" />
      </form>
    </div>
    {% endif %}
    <div class="mr-2">
      {% if user.is_authenticated %}
      <a href="{% url 'filme:logout' %}">
        <button class="bg-red-600 text-white py-1 px-3 rounded-md">Sair</button>
      </a>
      {% else %}
      <a href="{% url 'filme:login' %}">
        <button class="bg-red-600 text-white py-1 px-3 rounded-md">
          Login
        </button>
      </a>
      {% endif %}
    </div>

    {% if user.is_authenticated %}
    <div class="mr-2">
      <a href="{% url 'filme:editarperfil' request.user.id %}">
        <button class="bg-red-600 text-white py-1 px-3 rounded-md">
          Editar Perfil
        </button>
      </a>
    </div>
  </div>
  {% endif %}
</nav>